application: smsmybus
version: 8
runtime: python
api_version: 1

inbound_services:
- mail

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /dashboard
  static_files: dashboard.html
  upload: dashboard.html
  
- url: /_ah/mail/.+
  script: main.py
  login: admin
  
- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)
  
- url: /style.css
  static_files: style.css
  upload: style.css

- url: /jquery.timers-1.2.js
  static_files: jquery.timers-1.2.js
  upload: jquery.timers-1.2.js
  
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /crawlingtask
  script: main.py
  login: admin

- url: /loggingtask
  script: main.py
  login: admin

- url: /sendsmstask
  script: main.py
  login: admin
  
- url: /configure
  script: main.py
  login: admin
    
- url: /cleandb
  script: main.py
  login: admin
      
#
# ADMIN access
#      
- url: /admin.*
  script: admin.py
  login: admin

# 
# PHONE access
#
- url: /phone/.*
  script: phone.py

#
# TWITTER access
#
- url: /twitter/.*
  script: twitter.py

#
# REST access
#
- url: /rest/.*
  script: rest.py

#
# catch all...
#
- url: /.*
  script: main.py

