application: smsmybus
version: 13
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

inbound_services:
- mail
- xmpp_message

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /motherfools
  static_files: motherfools/index.html
  upload: motherfools/index.html

- url: /motherfools/index-api.html
  static_files: motherfools/index-api.html
  upload: motherfools/index-api.html
    
- url: /dashboard
  static_files: dashboard.html
  upload: dashboard.html
  
- url: /_ah/mail/.+
  script: main.py
  login: admin
  
- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)
  
- url: /style.css
  static_files: style.css
  upload: style.css

- url: /jquery.timers-1.2.js
  static_files: jquery.timers-1.2.js
  upload: jquery.timers-1.2.js
  
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /apple-touch-icon.png
  static_files: img/apple-touch-icon.png
  upload: img/apple-touch-icon.png
    
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /loggingtask
  script: main.py
  login: admin

- url: /sendsmstask
  script: main.py
  login: admin
  
- url: /cleandb
  script: main.py
  login: admin
      
- url: /rest/prefetch/.*
  script: rest.py
  login: admin

# AppStats interface
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
    
#
# ADMIN access
#      
- url: /admin.*
  script: admin.py
  login: admin

# 
# PHONE access
#
- url: /phone/.*
  script: phone.py

#
# TWITTER access
#
- url: /twitter/.*
  script: twitter.py

#
# REST access
#
- url: /rest/.*
  script: rest.py

#
# data CRAWLER access
#
- url: /crawl/.*
  script: crawl/prefetch.py
  login: admin

- url: /configure
  script: crawl/crawler.py
  login: admin

- url: /configuregeo
  script: crawl/crawler.py
  login: admin

- url: /storethestop
  script: crawl/crawler.py
  login: admin
    
- url: /crawlingtask
  script: crawl/crawler.py
  login: admin
  
- url: /crawlinggeotask
  script: crawl/crawler.py
  login: admin
  
- url: /routelist/.*
  script: crawl/crawler.py
  login: admin

#
# API access
- url: /api/
  static_files: api/index.html
  upload: api/index.html
  
- url: /api/style.css
  static_files: api/style.css
  upload: api/style.css
  
- url: /api/v1/getarrivals
  script: api/v1/getarrivals.py

- url: /api/v1/createdevkey
  script: api/v1/getarrivals.py
  login: admin
  
# drop table
- url: /droptable/.*
  script: crawl/crawler.py
  login: admin
  
#
# catch all...
#
- url: /.*
  script: main.py

