application: smsmybus-hrd
version: aggregatorfix
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

inbound_services:
- mail
- xmpp_message

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /gadgets/metro/.*
  script: gadgets/gadget.py
  
- url: /gadgets/stop.xml
  static_files: gadgets/stop.xml
  upload: gadgets/stop.xml

- url: /gadgets/style.css
  static_files: gadgets/style.css
  upload: gadgets/style.css

- url: /js
  static_dir: js
  
- url: /css
  static_dir: css
  
- url: /_ah/mail/.+
  script: main.py
  login: admin
  
- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)
  
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /apple-touch-icon.png
  static_files: img/apple-touch-icon.png
  upload: img/apple-touch-icon.png
    
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /aggr/.*
  script: aggregator/aggregation.py
    
- url: /loggingtask
  script: main.py
  login: admin

- url: /sendsmstask
  script: main.py
  login: admin
  
- url: /cleandb
  script: main.py
  login: admin
      
- url: /rest/prefetch/.*
  script: rest.py
  login: admin

# AppStats interface
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
    
#
# ADMIN access
#      
- url: /admin.*
  script: admin.py
  login: admin

# 
# PHONE access
#
- url: /phone/.*
  script: phone.py

#
# TWITTER access
#
- url: /twitter/.*
  script: twitter.py

#
# REST access
#
- url: /rest/.*
  script: rest.py

#
# data CRAWLER access
#
- url: /crawl/.*
  script: crawl/crawl-stop-locations.py
  login: admin

- url: /routelist/.*
  script: crawl/crawler.py
  login: admin

#
# API access
- url: /api/v1/getarrivals
  script: api/v1/getarrivals.py

- url: /api/v1/get(stops|nearbystops|stoplocation|debug)
  script: api/v1/getstops.py

- url: /api/location
  script: api/feed.py
  login: admin

- url: /api/(.*\.(html|css|js))
  static_files: api/\1
  upload: api/(.*\.(html|css|js))
  
- url: /api/v1/createdevkey/.*
  script: api/v1/getarrivals.py
  login: admin
  
- url: /api.*
  static_files: api/index.html
  upload: api/index.html

# drop table
- url: /droptable/.*
  script: crawl/crawler.py
  login: admin
  
# debug : create entities
- url: /debug/create/.*
  script: crawl/crawler.py
  login: admin

# debug : start table drop in background
- url: /debug/drop/DeveloperRequest
  script: crawl/crawler.py
  login: admin
#
# Custom displays
- url: /motherfools.*
  static_files: motherfools/index.html
  upload: motherfools/index.html

- url: /motherfools/index-api.html
  static_files: motherfools/index-api.html
  upload: motherfools/index-api.html
    
- url: /supranet.*
  static_files: supranet/index.html
  upload: supranet/index.html
  
- url: /sector67.*
  static_files: sector67/index.html
  upload: sector67/index.html
 
- url: /labs/.*
  script: labs/mapit.py
   
#
# catch all...
#
- url: /.*
  script: main.py

