application: smsmybus
version: 17
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

inbound_services:
- mail
- xmpp_message

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /gadgets
  static_dir: gadgets
  
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css
  
- url: /labs/map
  script: labs/mapit.py

- url: /labs/maptask
  script: labs/mapit.py
  login: admin
  
- url: /motherfools
  static_files: motherfools/index.html
  upload: motherfools/index.html

- url: /motherfools/index-api.html
  static_files: motherfools/index-api.html
  upload: motherfools/index-api.html
    
- url: /supranet.*
  static_files: supranet/index.html
  upload: supranet/index.html
  
- url: /sector67.*
  static_files: sector67/index.html
  upload: sector67/index.html

- url: /dashboard
  static_files: dashboard.html
  upload: dashboard.html
  
- url: /_ah/mail/.+
  script: main.py
  login: admin
  
- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)
  
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /apple-touch-icon.png
  static_files: img/apple-touch-icon.png
  upload: img/apple-touch-icon.png
    
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /loggingtask
  script: main.py
  login: admin

- url: /sendsmstask
  script: main.py
  login: admin
  
- url: /cleandb
  script: main.py
  login: admin
      
- url: /rest/prefetch/.*
  script: rest.py
  login: admin

# AppStats interface
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
    
#
# ADMIN access
#      
- url: /admin.*
  script: admin.py
  login: admin

# 
# PHONE access
#
- url: /phone/.*
  script: phone.py

#
# TWITTER access
#
- url: /twitter/.*
  script: twitter.py

#
# REST access
#
- url: /rest/.*
  script: rest.py

#
# data CRAWLER access
#
- url: /crawl/.*
  script: crawl/crawl-stop-locations.py
  login: admin

- url: /routelist/.*
  script: crawl/crawler.py
  login: admin

#
# API access
- url: /api/
  static_files: api/index.html
  upload: api/index.html

- url: /api/locations.html
  static_files: api/locations.html
  upload: api/locations.html

- url: /api/notifications.html
  static_files: api/notifications.html
  upload: api/notifications.html
    
- url: /api/routes.html
  static_files: api/routes.html
  upload: api/routes.html
  
- url: /api/schedule.html
  static_files: api/schedule.html
  upload: api/schedule.html
  
- url: /api/style.css
  static_files: api/style.css
  upload: api/style.css
  
- url: /api/v1/getarrivals
  script: api/v1/getarrivals.py

- url: /api/v1/createdevkey
  script: api/v1/getarrivals.py
  login: admin
  
# drop table
- url: /droptable/.*
  script: crawl/crawler.py
  login: admin
  
#
# catch all...
#
- url: /.*
  script: main.py

